server:
  status_codes:
    api:      400
    console:  200
  domains:
    canonical:
      console:  "console.s3.{{ DOMAIN_PRIMARY }}"
      api:      "api.s3.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    flags: {}
    whitelist:
      font-src: []
      connect-src: [] 
compose:
  services:
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true

    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    minio:
      backup:
        no_stop_required: false
      image:              quay.io/minio/minio
      version:            latest
      name:               minio
      min_storage:        "20GB"
      cpus:               "2.0"
      mem_reservation:    "2g"
      mem_limit:          "4g"
      pids_limit:         2048
    redis:
      backup:
        disabled: true
      enabled: false
    css:
      enabled: true
      shared: true
    javascript:
      enabled: false
      shared: true
    ollama:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes: 
    data:      minio_data
credentials: {}
