server:
  csp:
    flags:
      script-src-attr:
        unsafe-eval:    true
      script-src-elem:
        unsafe-inline:  true
        unsafe-eval:    true
      style-src-attr:
        unsafe-inline:  true
  domains:
    canonical:
      - "docs.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    sphinx:
      image:            "ghcr.io/kevinveenbirkenbach/infinito-sphinx"
      version:          "latest"
      min_storage:      "1GB"
      backup:
        no_stop_required: true
      port:               8000
      name:               "sphinx"
    css:
      enabled: true
      shared: true
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
