# Selected workstation user key (in users dict)
USER_WORKSTATION_KEY: "{{ WORKSTATION_USER }}"
USER_WORKSTATION_CONFIG: "{{ lookup('users', USER_WORKSTATION_KEY) }}"

# Workstation username on the system
USER_WORKSTATION_USERNAME: "{{ USER_WORKSTATION_CONFIG.username }}"

# Optional UID/GID
USER_WORKSTATION_UID: "{{ USER_WORKSTATION_CONFIG.uid | default(omit) }}"
USER_WORKSTATION_GID: "{{ USER_WORKSTATION_CONFIG.gid | default(omit) }}"

# Shell and groups
USER_WORKSTATION_DEFAULT_SHELL: "/bin/bash"
USER_WORKSTATION_SHELL: "{{ USER_WORKSTATION_CONFIG.shell | default(USER_WORKSTATION_DEFAULT_SHELL) }}"
USER_WORKSTATION_GROUPS: "{{ USER_WORKSTATION_CONFIG.groups | default([]) }}"

# Behavior toggles
USER_WORKSTATION_ENABLE_SUDO: true
USER_WORKSTATION_SET_PASSWORD: false
