server:
  domains:
    canonical:
      - "phpldapadmin.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    phpldapadmin:
      image:    "phpldapadmin/phpldapadmin"
      version:  "latest"
      min_storage: "1GB"
    oauth2:
      enabled: true
      shared: true
      origin:
        host: application  # Needs to be the same as webinterface
        port: 8080         # application port
      allowed_groups:
        - "{{ [RBAC.GROUP.NAME, 'web-app-phpldapadmin-administrator'] | path_join }}"
    css:
      enabled: true
      shared: true
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
