server:
  domains:
    canonical:
      - jenkins.{{ DOMAIN_PRIMARY }}
    aliases: []
compose:
  services:
    logout:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
