ldap:
  filters:
    administrators:   False   # Set true to filter administrators
    users:            False   # Set true to filter users
server:
  csp:
    flags:
      script-src-elem:
        unsafe-inline: true
      style-src-attr:
        unsafe-inline: true
    whitelist:
      font-src:
        - "data:"
  domains:
    canonical:
      - "open.project.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    postgres:
      enabled: true
      shared: true
    web:
      name:               openproject-web
      image:              openproject/openproject
      version:            "17"
      backup:
        no_stop_required: true
      cpus:               "3.0"
      mem_reservation:    "3g"
      mem_limit:          "4g"
      pids_limit:         2048
    seeder:
      name:               openproject-seeder
      cpus:               "0.3"
      mem_reservation:    "256m"
      mem_limit:          "512m"
      pids_limit:         256
    cron:
      name:               openproject-cron
      cpus:               "0.3"
      mem_reservation:    "256m"
      mem_limit:          "512m"
      pids_limit:         256
    worker:
      name:               openproject-worker
      cpus:               "2.0"
      mem_reservation:    "2g"
      mem_limit:          "3g"
      pids_limit:         2048
    proxy:
      name:               openproject-proxy
      cpus:               "0.3"
      mem_reservation:    "256m"
      mem_limit:          "512m"
      pids_limit:         256
    cache:
      name:               openproject-cache
      cpus:               "0.3"
      mem_reservation:    "512m"
      mem_limit:          "512m"
      pids_limit:         256
    oauth2:
      enabled: true
      shared: true
      origin:
        host:             "proxy"
        port:             "80"
      acl:
        whitelist:
          - "/users/me"           # Necessary for Nextcloud Plugin to work
          - "/api/"               # Necessary for Nextcloud Plugin to work
          - "/oauth/token"        # Necessary for Nextcloud Plugin to work
    css:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:                 "openproject_data"
