server:
  domains:
    canonical:
      openwebui:  "chat.ai.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    flags:
      script-src-elem:
        unsafe-inline:  true
    whitelist:
      font-src: [] 
      connect-src: [] 
compose:
  services:
    oidc:
      enabled: true
      shared: true
    ldap:
      enabled: false
      shared: false
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    openwebui:
      backup:
        no_stop_required: true
      image:              ghcr.io/open-webui/open-webui
      version:            main
      name:               open-webui
      min_storage:        "5GB"
      offline_mode:       false
      hf_hub_offline:     false
      cpus:               2.0
      mem_reservation:    1g
      mem_limit:          4g
      pids_limit:         4096
    redis:
      backup:
        disabled: true
      enabled: false
    css:
      enabled: false
      shared: true
    javascript:
      enabled: false
      shared: true
    ollama:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes: 
    openwebui:  ai_openwebui_data
credentials: {}
