- name: "TLS | Apply tls layer"
  include_role:
    name: sys-front-tls
  when: lookup('tls', domain, 'enabled') | bool
  vars:
    application_id: "{{ domain }}"

- name: "Deploying NGINX redirect configuration for '{{ domain }}'"
  template:
    src:  redirect-domain.conf.j2
    dest: "{{ lookup('nginx', 'files.domain', domain) }}"
  notify: restart openresty
  vars:
    application_id: "{{ domain }}"
