server:
  config_upstream_url: "https://ip.bsky.app/config" # nocheck: url
  status_codes:
    web: 405
  domains:
    aliases: []
    canonical:
      web:  "web.bluesky.{{ DOMAIN_PRIMARY }}"
      api:  "api.bluesky.{{ DOMAIN_PRIMARY }}"
      view: "view.bluesky.{{ DOMAIN_PRIMARY }}"
  csp:
    whitelist:
      connect-src:
        - "api.bluesky.{{ DOMAIN_PRIMARY }}"
        - "https://plc.directory"
        - "https://bsky.social"
        - "https://api.bsky.app"
        - "https://public.api.bsky.app"
        - "https://events.bsky.app"
        - "https://statsigapi.net"  # nocheck: url
        - "https://ip.bsky.app"  # nocheck: url
        - "https://video.bsky.app"
        - "https://bsky.app"
        - "wss://bsky.network"
        - "wss://*.bsky.app"
      media-src:
        - "blob:"
      worker-src:
        - "blob:"
compose:
  services:
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    # noqa: shared
    web:
      enabled: true  # @see https://github.com/bluesky-social/social-app
    view:
      enabled: false
    pds:
      image:    "ghcr.io/bluesky-social/pds"
      version:  "latest"
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    pds_data:   "pds_data"
