server:
  domains:
    canonical:
      - "social.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    flags:
      script-src-elem:
        unsafe-inline:  true
      script-src-attr:
        unsafe-inline:  true
        unsafe-eval:    true
      style-src-attr:
        unsafe-inline:  true
addons:
  keycloakpassword: {}
  ldapauth: {}
compose:
  services:
    friendica:
      image:        'friendica'
      version:      'latest'
      min_storage:  '10GB'
    oidc:
      enabled:  false
      shared:   false
    logout:
      enabled:  true
      shared: true
    ldap:
      enabled:  true
      shared:   true
    dashboard:
      enabled:  true
      shared:   true
    matomo:
      enabled:  true
      shared:   true
    email:
      enabled: true
      shared: true
    mariadb:
      enabled: true
      shared: true
    oauth2:
      origin:
        host:   "application"
        port:   "80"
      enabled:  false
    css:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
