application_id:                 desk-nextcloud
nextcloud_user_home_directory:  "/home/{{ lookup('users', WORKSTATION_USER).username }}/"
nextcloud_cloud_fqdn:           "{{ lookup('config', application_id, 'credentials.cloud_fqdn') }}"
nextcloud_cloud_directory:      "{{ nextcloud_user_home_directory }}Clouds/{{ nextcloud_cloud_fqdn }}/{{ lookup('users', WORKSTATION_USER).username }}/"

nextcloud_dotlinker_folders:
  - Templates
  - Documents
  - Videos
  - Pictures
  - Music
  - Desktop
  - Software
  - Downloads
  - Workspaces
  - Books
  - Screenshots
