server:
  csp:
    flags:
      style-src-attr:
        unsafe-inline: true
      script-src-elem:
        unsafe-inline: true
  domains:
    aliases: []
    canonical:
      - phpmyadmin.{{ DOMAIN_PRIMARY }}
compose:
  services:
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: false
    matomo:
      enabled: true
      shared: true
    mariadb:
      enabled: true
      shared: true
    phpmyadmin:
      version:    "latest" # Use the latest phpmyadmin version
      name:       "phpmyadmin"
      image:      "phpmyadmin/phpmyadmin"
      min_storage: "1GB"
      # This is a high security risk. Just activate this option if you know what you're doing
      autologin:  false
    oauth2:
      enabled: true
      shared: true
      origin:
        port:   "80"
        host:   "application"
      allowed_groups:
        - "{{ [RBAC.GROUP.NAME, 'web-app-phpmyadmin-administrator'] | path_join }}"
    css:
      enabled: false
      shared: true
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
