# General
application_id:             "web-app-wordpress"
entity_name:                "{{ application_id | get_entity_name }}"

# WordPress
WORDPRESS_URL:                "{{ lookup('tls', application_id, 'url.base') }}"
WORDPRESS_TITLE:              "{{ lookup('config', application_id, 'compose.services.' ~ entity_name ~ '.title') }}"
WORDPRESS_MAX_UPLOAD_SIZE:    "{{ lookup('config', application_id, 'compose.services.' ~ entity_name ~ '.max_upload_size') }}"
WORDPRESS_CUSTOM_IMAGE:       "{{ entity_name }}_custom:{{ WORDPRESS_VERSION }}"
WORDPRESS_DOCKER_HTML_PATH:   "/var/www/html"
WORDPRESS_DOCKER_CONF_PATH:   "{{ WORDPRESS_CONFIG_PATH }}"
WORDPRESS_VERSION:            "{{ lookup('config', application_id, 'compose.services.' ~ entity_name ~ '.version') }}"
WORDPRESS_IMAGE:              "{{ lookup('config', application_id, 'compose.services.' ~ entity_name ~ '.image') }}"
WORDPRESS_CONTAINER:          "{{ lookup('config', application_id, 'compose.services.' ~ entity_name ~ '.name') }}"
WORDPRESS_VOLUME:             "{{ lookup('config', application_id, 'compose.volumes.data') }}"
WORDPRESS_DOMAINS:            "{{ lookup('config', application_id, 'server.domains.canonical') }}"
WORDPRESS_PLUGINS:            "{{ lookup('config', application_id, 'compose.services.' ~ entity_name ~ '.plugins') | dict2items }}"
WORDPRESS_USER:               "www-data"

# Email
WORDPRESS_MSMTP_SRC:          "{{ [ playbook_dir, 'roles/sys-svc-mail-msmtp/templates/msmtprc.conf.j2' ] | path_join }}"
WORDPRESS_MSMTP_ABS:          "{{ [ lookup('container', application_id, 'directories.config'), 'msmtprc.conf'] | path_join }}"

# Config
WORDPRESS_CONFIG_FILE:        "wp-config.php"
WORDPRESS_CONFIG_PATH:        "{{ [WORDPRESS_DOCKER_HTML_PATH, WORDPRESS_CONFIG_FILE] | path_join }}"
WORDPRESS_CONFIG_UPLD_REL:    "config/upload.ini"
WORDPRESS_CONFIG_UPLD_ABS:    "{{ [lookup('container', application_id, 'directories.instance'), WORDPRESS_CONFIG_UPLD_REL ] | path_join }}"

# User 
WORDPRESS_ADMIN_EMAIL:        "{{ lookup('config', application_id, 'users.administrator.email') }}"
WORDPRESS_ADMIN_USER:         "{{ lookup('config', application_id, 'users.administrator.username') }}"
WORDPRESS_ADMIN_PASSWORD:     "{{ lookup('config', application_id, 'credentials.administrator_password') }}"
