server:
  csp:
    whitelist:
      script-src-elem:
        - https://cdnjs.cloudflare.com
        - https://code.jquery.com
        - https://cdn.jsdelivr.net
      style-src-elem:
        - https://cdnjs.cloudflare.com
        - https://cdn.jsdelivr.net
      font-src:
        - https://cdnjs.cloudflare.com
      frame-src:
         # Makes sense that all of the website content is available in the navigator
        - "*.{{ DOMAIN_PRIMARY }}"
    flags:
      style-src-attr:
        unsafe-inline:  true
      script-src-attr:
        unsafe-eval:    true
      script-src-elem:
        unsafe-inline:  true
  domains:
    canonical:
      - "slides.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
