server:
  domains:
    canonical:
      - "inventory.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    flags:
      script-src-attr:
        unsafe-inline:  true
        unsafe-eval:    true
      script-src-elem:
        unsafe-inline:  true
      style-src-attr:
        unsafe-inline:  true
    whitelist:
      font-src:
        - "data:"
compose:
  services:
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled: true
    mariadb:
      enabled: true
      shared: true
    snipe-it:
      version:          "latest-alpine"
      name:             "snipe-it"
      image:            "snipe/snipe-it"
      min_storage:      "8GB"
      cpus:             "1.0"
      mem_reservation:  "256m"
      mem_limit:        "2g"
      pids_limit:       512
    oauth2:
      enabled: true
      shared: true
      origin:
        host:   "snipe-it"
        port:   "80"
      acl:
        blacklist:
          - "/login"
    css:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:       "snipe-it_data"
    
