---
- name: "Include setup for domain '{{ domain }}'"
  include_role:
    name: sys-stk-front-proxy
  loop: "{{ lookup('domains', 'web-app-mastodon') }}"
  loop_control:
    loop_var: domain
  vars:
    http_port:                      "{{ ports.localhost.http[application_id] }}"
    webserver_websocket_location:   "/api/v1/streaming"
    websocket_port:       "{{ ports.localhost.websocket[application_id] }}"
    webserver_client_max_body_size: "80m"
    webserver_vhost_flavour:        "ws_generic"

- name: "load docker and db for {{ application_id }}"
  include_role:
    name: sys-stk-backend
  vars:
    docker_compose_flush_handlers: false

- name: "MASTODON | Apply overrides"
  include_tasks: 00_overrides.yml
  when: MASTODON_HTTP_ONLY_ENABLED | bool

- name: Flush handlers to start Mastodon after migration 
  meta: flush_handlers

- name: "start setup procedures for mastodon"
  include_tasks: 01_setup.yml

- name: "Wait for Mastodon"
  include_tasks: 02_wait.yml

- name: "Cleanup Mastodon caches when MODE_CLEANUP is true"
  include_tasks: 03_cleanup.yml
  when: MODE_CLEANUP | bool

- name: "Include administrator routines for '{{ application_id }}'"
  include_tasks: 04_administrator.yml
