server:
  csp:
    flags:
      style-src-attr:
        unsafe-inline: true
      script-src-elem:
        unsafe-inline: true
    whitelist:
      font-src:
        - "data:"
  domains:
    canonical:
      - pgadmin.{{ DOMAIN_PRIMARY }}
    aliases: []
compose:
  services:
    pgadmin:
      image:                    "dpage/pgadmin4"
      version:                  "latest"
      min_storage:              "1GB"
      server_mode:              False             # If true then the preconfigured database file is loaded. Recommended False. True is a security risk.
      master_password_required: True              # Master password is required. Recommended True. False is a security risk.
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    postgres:
      enabled: true
      shared: true
    oauth2:
      enabled: true
      shared: true
      origin:
        host: "application"
        port: "80"
      allowed_groups:
        - "{{ [RBAC.GROUP.NAME, 'web-app-pgadmin-administrator'] | path_join }}"
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
