- name: install arduino developer tools
  package:
    name:
      - arduino
      - arduino-docs
    state: present

- name: "Adding user {{ lookup('users', WORKSTATION_USER).username }} to relevant arduino usergroups"
  ansible.builtin.user:
    name: "{{ lookup('users', WORKSTATION_USER).username }}"
    groups:
      - uucp
      - lock
    append: true
