---
- services:
    container_backup:
      enabled: true
    sso:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    tor:
      enabled: true

- services:
    container_backup:
      enabled: false
      shared: false # nocheck: variants-static-override backup shared stays literally true
    sso:
      enabled: false
      shared: false
    ldap:
      enabled: false
      shared: false
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: false
      shared: false
    matomo:
      enabled: false
      shared: false
    prometheus:
      enabled: false
      shared: false
    css:
      enabled: false
      shared: false
    tor:
      enabled: true
