credentials: {}
compose:
  services:
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled:      true
    postgres:
      enabled: true
      shared: true
    pretix:
      image:        pretix/standalone
      version:      stable
      name:         pretix
      min_storage:  "10GB"
      backup:
        no_stop_required: true
      cpus:               "2.0"
      mem_reservation:    "1.5g"
      mem_limit:          "2g"
      pids_limit:         1024
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:           "pretix_data"
    config:         "pretix_config"
server:
  csp:
    whitelist:      {}
    flags:          {}
  domains:
    canonical:
      - "ticket.shop.{{ DOMAIN_PRIMARY }}"
    aliases: []
rbac:
  roles: {}
plugins:
  oidc:
    version: "2.3.1"
