
credentials: {}
compose:
  services:
    oidc:
      enabled: false
      shared: false
    logout:
      enabled: true
      shared: true

    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    postgres:
      enabled: true
      shared: true
    jira:
      image:            atlassian/jira-software
      version:          latest
      name:             jira
      min_storage:      "20GB"
      cpus:             "2.0"
      mem_reservation:  "4g"
      mem_limit:        "6g"
      pids_limit:       2048
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:           "jira_data"
server:
  csp:
    whitelist:      {}
    flags:
      script-src-elem:
        unsafe-inline:  true
        unsafe-eval:    true
      script-src-attr:
        unsafe-inline:  true
        unsafe-eval:    true
  domains:
    canonical:
      - "jira.{{ DOMAIN_PRIMARY }}"
    aliases: []
  status_codes:
    default: 405
rbac:
  roles: {}
