
credentials: {}
compose:
  services:
    libretranslate:
      enabled: false
      shared: true
      image:    libretranslate/libretranslate
      version: latest
      min_storage: "5GB"
    oauth2:
      enabled: false
    logout:
      enabled: false
      shared: false

    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    redis:
      backup:
        disabled: true
      enabled:      false   # Enable Redis
    css:
      enabled: true
      shared: true
    recaptcha:
      enabled: false
    javascript:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
server:
  csp:
    whitelist:        {}      # URL's which should be whitelisted
    flags:            {}      # Flags which should be set
  domains:
    canonical:
      - "libretranslate.{{ DOMAIN_PRIMARY }}"
    aliases:          []      # Alias redirections to the first element of the canonical domains
rbac:
  roles: {}
