- name: Check if the SSH key for root already exists
  ansible.builtin.stat:
    path: "{{ USER_ROOT_SSH_KEY_PUBLIC }}"
  register: ssh_key

- name: "Include routine to create {{ USER_ROOT_SSH_KEY_PUBLIC }}"
  include_tasks: 02_ssh.yml
  when: not ssh_key.stat.exists

- name: "embed user routines for {{ role_path | basename }}"
  include_role:
    name: user
  vars:
    user_key: "root"
    user_config: >-
      {{
        lookup('users', 'root', {})
        | combine(
            {
              'authorized_keys': (
                lookup('users', 'root', {}).authorized_keys | default([])
              )
            },
            recursive=True
          )
      }}

- name: "create {{ DIR_SCRIPTS_ROOT }}"
  file:
    path: "{{ DIR_SCRIPTS_ROOT }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- include_tasks: utils/once/flag.yml
