server:
  csp:
    flags:
      style-src-attr:
        unsafe-inline:  true
      script-src-elem:
        unsafe-inline:  true
      script-src-attr:
        unsafe-eval:    true
    whitelist:
      worker-src:
        - "blob:"
      font-src:
        - "data:"
        - "https://fonts.bunny.net"
      script-src-elem:
        - "https://cdn.gtranslate.net"    # Necessary for translation plugins
        - "https://translate.google.com"  # Necessary for translation plugins
        - "blog.{{ DOMAIN_PRIMARY }}"
      style-src-elem:
        - "https://fonts.bunny.net"
      frame-src:
        - "blob:"
        - "*"
  domains:
    canonical:
      - "blog.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    mariadb:
      enabled: true
      shared: true
    discourse:
      enabled: false
      shared: true
    wordpress:
      version:            latest
      image:              wordpress
      name:               wordpress
      min_storage:        "8GB"
      backup:
        no_stop_required:   true
      cpus:                 1
      mem_reservation:      0.5g
      mem_limit:            1.5g
      pids_limit:           512
      title:                "Blog by {{ service_provider.platform.titel }}"
      # Low default upload size, because you should use Peertube for Videos and Funkwhale for Audio files
      max_upload_size:      "256M"
      plugins:
        wp-discourse:
          enabled:          "{{ lookup('service', 'discourse').required | bool }}"
        daggerhart-openid-connect-generic:
          enabled:          true
        activitypub:
          enabled:          true
    css:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes: 
    data:                 wordpress_data
rbac:
  roles:
    subscriber:
      description: "Can read posts and leave comments but cannot write or manage content"
    author:
      description: "Can write and manage own posts"
    contributor:
      description: "Can write and submit posts for review but cannot publish"
    editor:
      description: "Can publish and manage all posts, including those by other users"
    administrator:
      description: "Has full administrative access: manage themes, plugins, settings, and users"
