---
- name: Ensure Docker daemon is running on host
  ansible.builtin.service:
    name: docker.service
    state:  restarted
    enabled: yes
  listen: container manager restart

- name: Ensure Docker-In-Docker DNS works
  ansible.builtin.script: "{{ role_path }}/files/test-dns.sh"
  register: docker_in_docker_dns_check
  until: docker_in_docker_dns_check is succeeded
  retries: 7
  delay: 20
  listen: container manager restart
  run_once: true
  when:
    - DOCKER_IN_CONTAINER | bool
    - MODE_DEBUG | bool
  environment:
    BUSYBOX_IMAGE: "{{ lookup('image', 'busybox', 'ref') }}"
    NODE_IMAGE: "{{ lookup('image', 'node', 'ref') }}"
