server:
  csp:
    flags:
      script-src-elem:
        unsafe-inline:            true
      style-src-attr:
        unsafe-inline:            true
    whitelist: {}
  domains:
    aliases: []
    canonical:
      - prometheus.{{ DOMAIN_PRIMARY }}
  status_codes:
    default:                      [200, 302]
compose:
  services:
    oidc:
      enabled:                    false
    oauth2:
      enabled:                    true
      shared:                     true
      origin:
        host:                     "application"
        port:                     "9090"
      allowed_groups:
        - "{{ [RBAC.GROUP.NAME, 'web-app-prometheus-administrator'] | path_join }}"
    logout:
      enabled:                    true
      shared:                     true
    dashboard:
      enabled:                    true
      shared:                     true
    matomo:
      enabled:                    true
      shared:                     true
    redis:
      enabled:                    false
    css:
      enabled:                    true
      shared:                     true
    prometheus:
      image:                      "prom/prometheus"
      version:                    "v3.11.3"
      name:                       "prometheus"
      cpus:                       "0.5"
      mem_reservation:            "256m"
      mem_limit:                  "512m"
      pids_limit:                 256
  volumes:
    data:                         "prometheus_data"
