credentials: {}
compose:
  services:
    oidc:
      enabled: false
      shared: false
    logout:
      enabled: true
      shared: true

    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    postgres:
      enabled: true
      shared: true
    confluence:
      image:            atlassian/confluence
      version:          latest
      name:             confluence
      min_storage:      "20GB"
      cpus:             "3.0"
      mem_reservation:  "6g"
      mem_limit:        "8g"
      pids_limit:       2048
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:           "confluence_data"
server:
  status_codes:
    default: 302
  csp:
    whitelist:      {}
    flags:
      script-src-elem:
        unsafe-inline:  true
      script-src-attr:
        unsafe-inline:  true
  domains:
    canonical:
      - "c.wiki.{{ DOMAIN_PRIMARY }}"
    aliases: []
rbac:
  roles: {}
truststore_enabled: false
