server:
  domains:
    canonical:
      - "s.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    flags:
      style-src-attr:
        unsafe-inline:  true
      script-src-elem:
        unsafe-inline:  true
      script-src-attr:
        unsafe-inline:  true
  locations:
    admin:  "/admin/"
  status_codes:
    default: 301
compose:
  services:
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    mariadb:
      enabled: true
      shared: true
    yourls: 
      version:    "latest"
      name:       "yourls"
      image:      "yourls"
      min_storage: "1GB"
    oauth2:
      enabled: true
      shared: true
      origin:
        host: "application"
        port: "80"
      allowed_groups:
        - "{{ [RBAC.GROUP.NAME, 'web-app-yourls-administrator'] | path_join }}"
      acl:
        blacklist:
          - "{{ lookup('config', 'web-app-yourls', 'server.locations.admin') }}" # Protects the admin area
    css:
      enabled: true
      shared: true
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
