server:
  csp:
    flags:
      script-src-elem:
        unsafe-inline: true
      script-src-attr:
        unsafe-inline: true
      style-src-attr:
        unsafe-inline: true
    whitelist:
      frame-src:
        - "*" # For frontend channel logout it's necessary that iframes can be loaded
  domains:
    canonical:
      - "auth.{{ DOMAIN_PRIMARY }}"
    aliases: []
scopes:
  nextcloud:  nextcloud

compose:
  services:
    logout:
      enabled:  false
      shared:   false
    ldap:
      enabled:  true
      shared:   true
      sync:
        period:
          # Sync user attribute changes all 15 min  
          changes:  900
          # Sync everything daily
          full:     86400
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    keycloak:
      enabled:            false
      shared:             true
      provides:           oidc
      image:              "quay.io/keycloak/keycloak"
      version:            "latest"
      name:               "keycloak"
      min_storage:        "5GB"
      cpus:               "2.0"
      mem_reservation:    "2g"
      mem_limit:          "4g"
      pids_limit:         1024
      realm:
        import_enabled:       True
        totp_enabled:         True
      users:
        emails_verified: True
    postgres:
      enabled:          true
      shared:           true
    css:
      enabled: true
      shared: true
    recaptcha:
      enabled: "{{ RECAPTCHA_ENABLED | bool }}"
    prometheus:
      enabled: true
      shared: true
credentials:
  recaptcha:
    key:      "{{ CAPTCHA.RECAPTCHA.KEY | default('') }}"
    secret:   "{{ CAPTCHA.RECAPTCHA.SECRET | default('') }}"
accounts:
  bootstrap:
    username: "administrator"
  system:
    username: "{{ SOFTWARE_NAME | replace('.', '_') | lower }}"
