- name: install git
  package:
    name: git
    state: present
  become: true

- name: Install gitcon CLI system-wide via pip
  include_role:
    name: sys-pip-install
  vars:
    package_name: gitcon
    global_install: true

- when: run_once_desk_git is not defined
  block:
    - name: setup git (as workstation user)
      ansible.builtin.command:
        argv:
          - "{{ lookup('command_path', 'gitcon') }}"
          - --merge-option
          - rebase
          - --name
          - "{{ lookup('users', WORKSTATION_USER).firstname }} {{ lookup('users', WORKSTATION_USER).lastname }}"
          - --email
          - "{{ lookup('users', WORKSTATION_USER).email }}"
          - --website
          - "{{ lookup('users', WORKSTATION_USER).website }}"
          - --signing
          - gpg
          - --gpg-key
          - "{{ lookup('users', WORKSTATION_USER).gpg }}"
      become: true
      become_user: "{{ lookup('users', WORKSTATION_USER).username }}"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    - include_tasks: utils/once/flag.yml
