server:
  csp:
    whitelist: {}
  domains:
    canonical:
      - "magento.shop.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    oidc:
      enabled: false
      shared: false
    logout:
      enabled: true
      shared: true

    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    php:
      image:              "markoshust/magento-php"
      version:            "8.4-fpm"
      name:               "magento-php"
      backup:
        no_stop_required: true
    nginx:
      image:              "markoshust/magento-nginx"
      version:            "latest"
      name:               "magento-nginx"
      backup:
        no_stop_required: true
    # noqa: shared
    mariadb:
      shared:             false
      enabled:            true
      version:            "11.4"
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled:            true
    # noqa: shared
    search:
      enabled:            true
      image:              "opensearchproject/opensearch"
      version:            "latest"
      name:               "magento-opensearch"
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:                 "magento_data"
