compose:
  services:
    funkwhale:
      image:    "funkwhale/front"
      version:  "2.0.1"
      min_storage: "20GB"
    api:
      image:    "funkwhale/api"
      version:  "2.0.1"
    typesense:
      image:    "typesense/typesense"
      version:  "30.2"
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled: true
    postgres:
      enabled: true
      shared: true
    oauth2:
      origin:
        host: "front"
        port: "80"
      acl:
        blacklist:
          - "/login"
      enabled: false
    css:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
server:
  domains:
    canonical:
      - "audio.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:  
    flags:
      style-src-attr:
        unsafe-inline:  true
    whitelist:
      font-src:
        -  "data:"
