# General
application_id:       "web-app-bridgy-fed"

# Container
container_port:       8080
domain:               "{{ container_hostname }}"
http_port:            "{{ ports.localhost.http[application_id] }}"
container_hostname:   "{{ lookup('domain',application_id) }}"

# App container
BRIDGY_CONTAINER:     "{{ lookup('config', application_id, 'compose.services.application.name') }}"
BRIDGY_IMAGE:         "{{ lookup('config', application_id, 'compose.services.application.image') }}"
BRIDGY_VERSION:       "{{ lookup('config', application_id, 'compose.services.application.version')}}"

BRIDGY_ADMIN_EMAIL:   "{{ lookup('users', 'administrator').email }}"

# Source
BRIDGY_REPO_URL:      "{{ lookup('config', application_id, 'compose.services.application.repository') }}"
BRIDGY_REPO_BRANCH:   "{{ lookup('config', application_id, 'compose.services.application.branch') }}"

# Runtime env defaults for Bridgy Fed (see upstream README)
BRIDGY_APPVIEW_HOST:  "api.bsky.app"
BRIDGY_PLC_HOST:      "plc.directory"
BRIDGY_BGS_HOST:      "bsky.network"
BRIDGY_PDS_HOST:      "atproto.brid.gy"
