---
- name: "load docker and proxy for '{{ application_id }}'"
  include_role:
    name: sys-stk-backend
  vars:
    docker_compose_flush_handlers: false

- name: "Deploy prometheus nginx http-block config to {{ lookup('nginx','directories.configuration.global') }}prometheus.conf"
  template:
    src: "roles/web-app-prometheus/templates/nginx/prometheus.conf.j2"
    dest: "{{ [ lookup('nginx','directories.configuration.global'), 'prometheus.conf' ] | path_join }}"
    mode: "0644"
  notify: restart openresty

- name: "Render prometheus scrape config to {{ PROMETHEUS_CONFIG_HOST }}"
  template:
    src: configuration/prometheus.yml.j2
    dest: "{{ PROMETHEUS_CONFIG_HOST }}"
    mode: "0644"
  notify: compose up

- name: "Render blackbox exporter config to {{ BLACKBOX_CONFIG_HOST }}"
  template:
    src: configuration/blackbox.yml.j2
    dest: "{{ BLACKBOX_CONFIG_HOST }}"
    mode: "0644"
  notify: compose up

- name: "Render alertmanager config to {{ ALERTMANAGER_CONFIG_HOST }}"
  template:
    src: configuration/alertmanager.yml.j2
    dest: "{{ ALERTMANAGER_CONFIG_HOST }}"
    mode: "0644"
  notify: compose up

- name: "Render alert rules to {{ ALERT_RULES_CONFIG_HOST }}"
  template:
    src: configuration/alert_rules.yml.j2
    dest: "{{ ALERT_RULES_CONFIG_HOST }}"
    mode: "0644"
  notify: compose up

- name: "flush handlers for '{{ application_id }}'"
  meta: flush_handlers

- name: "Include role sys-stk-front-proxy for '{{ application_id }}'"
  include_role:
    name: sys-stk-front-proxy
  vars:
    domain:     "{{ lookup('domain', application_id) }}"
    http_port:  "{{ ports.localhost.http[application_id] }}"
