server:
  csp:
    whitelist:
      script-src-elem:
        - "https://cdnjs.cloudflare.com"
        - "https://cdn.jsdelivr.net"
      style-src-elem:
        - "https://cdn.jsdelivr.net"
        - "https://cdnjs.cloudflare.com"
      font-src:
        - "https://cdnjs.cloudflare.com"
        - "data:"
      connect-src:
        - "https://cdn.jsdelivr.net"
      frame-src:
        - "https://littlejs.{{ DOMAIN_PRIMARY }}"
    flags:
      style-src-attr:
        unsafe-inline:  true
      script-src-elem:
        unsafe-inline:  true
        unsafe-eval:    true
      script-src-attr:
        unsafe-inline:  true
        unsafe-eval:    true
  domains:
    canonical:
      - "littlejs.game.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    javascript:
      enabled: true
      shared: true
    littlejs:
      image:   nginx
      version: alpine
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
