server:
  status_codes:
    default:
      - 308
      - 302
  domains:
    canonical:
      - "onlyoffice.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    whitelist:
      frame-ancestors:
        - "*.{{ DOMAIN_PRIMARY }}"
      script-src-elem:
        - "https://fonts.googleapis.com"  # nocheck: url
      style-src-elem:
        - "https://fonts.googleapis.com"  # nocheck: url
      font-src:
        - "https://fonts.gstatic.com"  # nocheck: url
    flags:
      script-src-attr:
        unsafe-inline:  true
      script-src-elem:
        unsafe-inline:  true
        unsafe-eval:    true
compose:
  services:
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled: true
    postgres:
      enabled: true
      shared: true
    onlyoffice:
      enabled:          false
      shared:           true
      image:            "onlyoffice/documentserver"
      version:          "latest"
      name:             "onlyoffice"
      min_storage:      "20GB"
      cpus:             2
      mem_reservation:  "1g"
      # Raised due to failures in CI pipeline (Good luck approach)
      mem_limit:        "4g"
      pids_limit:       8192
      backup:
        no_stop_required: true
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:         onlyoffice_data          # /var/www/onlyoffice/Data
    logs:         onlyoffice_logs          # /var/log/onlyoffice
    fonts:        onlyoffice_fonts         # /usr/share/fonts/truetype/custom
    lib:          onlyoffice_lib           # /var/lib/onlyoffice
    rabbitmqdata: onlyoffice_rabbitmqdata  # /var/lib/rabbitmq
    
    # The redis and db volume are just dummy volumes and aren't used 
    pgdata:       onlyoffice_pgdata        # /var/lib/postgresql
    redisdata:    onlyoffice_redisdata     # /var/lib/redis
