configuration_file: "oauth2-proxy-keycloak.cfg" # Needs to be set true in the roles which use it
allowed_roles:      "admin"                     # Restrict it default to admin role. Use the vars/main.yml to open the specific role for other groups  
server:
  domains:
    canonical:
      - oauth2-proxy.{{ DOMAIN_PRIMARY }}
    aliases: []
compose:
  services:
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: false
    matomo:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    oauth2-proxy:
      image:    "quay.io/oauth2-proxy/oauth2-proxy"
      version:  "latest"
      min_storage: "1GB"
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
