credentials: {}
compose:
  services:
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: false
      shared: false
      trylocal: true # Allows local login if LDAP is down
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    redis:
      enabled:            false
      backup:
        disabled:         true
    postgres:
      enabled: true
      shared: true
    xwiki:
      image:              xwiki
      version:            lts-postgres-tomcat
      name:               xwiki
      min_storage:        "10GB"
      backup:
        no_stop_required: true
      cpus:               1.0
      mem_reservation:    1g
      mem_limit:          2g
      pids_limit:         1024
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:           "xwiki_data"
server:
  csp:
    whitelist:
      worker-src:
        - "blob:"
    flags:
      script-src-attr:
        unsafe-eval:    true
      script-src-elem:
        unsafe-inline:  true
  domains:
    canonical:
      - "x.wiki.{{ DOMAIN_PRIMARY }}"
    aliases: []
rbac:
  roles: {}
plugins:
  oidc:
    enabled: true
    shared: true
    items:
      - id: "org.xwiki.contrib.oidc:oidc-authenticator"
        version: "2.19.6"

  ldap:
    enabled: false
    items:
      - id: "org.xwiki.contrib.ldap:ldap-authenticator"
        version: "9.15.7"

  # Example for Matomo
  matomo:
    enabled: false
    items:
      - id: "org.xwiki.contrib:matomo"
        version: "1.0"
