- block:
    - name: Include dependency 'sys-svc-webserver-core'
      include_role:
        name: sys-svc-webserver-core
      vars:
        docker_git_repository_pull: false # Deactivated here to don't inhire this
      when: run_once_sys_svc_webserver_core is not defined
    - include_tasks: utils/once/flag.yml
  when: run_once_sys_front_inj_all is not defined

- name: "Setup CDN directories for '{{ domain }}'"
  include_role:
    name: sys-svc-cdn

- name: Build injection facts for '{{ domain }}'
  set_fact:
    inj_enabled: "{{ lookup('applications') | inj_enabled(application_id, SRV_WEB_INJ_COMP_FEATURES_ALL) }}"
    inj_head_features: "{{ SRV_WEB_INJ_COMP_FEATURES_ALL | inj_features('head') }}"
    inj_body_features: "{{ SRV_WEB_INJ_COMP_FEATURES_ALL | inj_features('body') }}"

- name: "Activate logout proxy for '{{ domain }}'"
  include_role:
    name: sys-front-inj-logout
    public: true
  when: inj_enabled.logout

- name: "Activate Dashboard iFrame notifier for '{{ domain }}'"
  include_role:
    name:   sys-front-inj-dashboard
    public: true
  when: inj_enabled.dashboard

- name: "Activate Corporate CSS for '{{ domain }}'"
  include_role:
    name: sys-front-inj-css
  when: inj_enabled.css

- name: "Activate Matomo Tracking for '{{ domain }}'"
  include_role:
    name: sys-front-inj-matomo
  when: inj_enabled.matomo

- name: "Activate Javascript for '{{ domain }}'"
  include_role:
    name: sys-front-inj-javascript
  when: inj_enabled.javascript
