server:
  domains:
    canonical:
      - "logout.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    flags:
      style-src-attr:
        unsafe-inline: true
      script-src-elem:
        unsafe-inline: true
    whitelist:
      connect-src:
        - "*.{{ DOMAIN_PRIMARY }}"
        - "{{ DOMAIN_PRIMARY }}"
        - "https://cdn.jsdelivr.net"
      script-src-elem:
        - "https://cdn.jsdelivr.net"
      style-src-elem:
        - "https://cdn.jsdelivr.net"
      frame-ancestors:
        - "auth.{{ DOMAIN_PRIMARY }}"
compose:
  services:
    logout:
      enabled:          false
      shared:           true
      image:            "ghcr.io/kevinveenbirkenbach/universal-logout"
      version:          "latest"
      name:             "logout"
      min_storage:      "1GB"
      cpus:             0.2
      mem_reservation:  "256m"
      mem_limit:        "512m"
      pids_limit:       128
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    javascript:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
