server:
  csp:
    flags:
      script-src-elem:
        unsafe-inline:            true
      style-src-attr:
        unsafe-inline:            true
    whitelist: {}
  domains:
    aliases: []
    canonical:
      - fider.{{ DOMAIN_PRIMARY }}
  status_codes:
    default:                      [200, 301, 302, 405]
compose:
  services:
    oidc:
      enabled:                    true
      shared:                     true
    email:
      enabled:                    true
      shared:                     true
    logout:
      enabled:                    true
      shared:                     true
    dashboard:
      enabled:                    true
      shared:                     true
    matomo:
      enabled:                    true
      shared:                     true
    postgres:
      enabled:                    true
      shared:                     true
    fider:
      image:                      "getfider/fider"
      version:                    "stable"
      name:                       "fider"
      container_port:             3000
      min_storage:                "1GB"
      backup:
        no_stop_required:         true
      cpus:                       "0.5"
      mem_reservation:            "128m"
      mem_limit:                  "512m"
      pids_limit:                 256
    oauth2:
      enabled:                    false
    redis:
      backup:
        disabled:                 true
      enabled:                    false
    css:
      enabled:                    true
      shared:                     true
    javascript:
      enabled:                    false
    prometheus:
      enabled: true
      shared: true
