# General
application_id:                 "web-app-minio"

# MINIO
# https://www.min.io/
MINIO_VERSION:                  "{{ lookup('config', application_id, 'compose.services.minio.version') }}"
MINIO_IMAGE:                    "{{ lookup('config', application_id, 'compose.services.minio.image') }}"
MINIO_CONTAINER:                "{{ lookup('config', application_id, 'compose.services.minio.name') }}"
MINIO_VOLUME:                   "{{ lookup('config', application_id, 'compose.volumes.data') }}"

## Api
MINIO_API_DOMAIN:               "{{ lookup('config', application_id, 'server.domains.canonical.api') }}"
MINIO_API_URL:                  "{{ lookup('tls', application_id, 'protocols.web') }}://{{ MINIO_API_DOMAIN }}"
MINIO_API_PORT_INTERNAL:        9000
MINIO_API_PORT_PUBLIC:          "{{ ports.localhost.http[application_id ~ '_api'] }}"

## Console
MINIO_CONSOLE_DOMAIN:           "{{ lookup('config', application_id, 'server.domains.canonical.console') }}"
MINIO_CONSOLE_URL:              "{{ lookup('tls', application_id, 'url.base') }}"
MINIO_CONSOLE_PORT_INTERNAL:    9001
MINIO_CONSOLE_PORT_PUBLIC:      "{{ ports.localhost.http[application_id ~ '_console'] }}"

## MC
MINIO_MC_IMAGE:                 "quay.io/minio/mc:latest"
MINIO_MC_INSECURE:              false   # set to true if you use self-signed TLS
MINIO_MC_SCHEME:                "{{ 'https' if (MINIO_API_URL is match('^https://')) else 'http' }}"
MINIO_MC_HOST_ONLY:             "{{ MINIO_API_URL | regex_replace('^https?://', '') }}"
MINIO_MC_USER:                  "{{ lookup('users', 'administrator').username | urlencode }}"
MINIO_MC_PASS:                  "{{ lookup('users', 'administrator').password | urlencode }}"
MINIO_MC_INSECURE_SUFFIX:       "{{ '?insecure=true' if (MINIO_MC_INSECURE | bool) else '' }}"
MINIO_MC_HOST_ENV:              "{{ MINIO_MC_SCHEME }}://{{ MINIO_MC_USER }}:{{ MINIO_MC_PASS }}@{{ MINIO_MC_HOST_ONLY }}{{ MINIO_MC_INSECURE_SUFFIX }}"

## OIDC
MINIO_OIDC_ENABLED:             "{{ lookup('config', application_id, 'compose.services.oidc.enabled') }}"
MINIO_OIDC_POLICY_NAME:         "{{ [ RBAC.GROUP.NAME, application_id ~ '-administrator' ] | path_join }}"
MINIO_OIDC_POLICY_CONTENT:      "{{ lookup('template', 'policy.json.j2') }}"

MINIO_FRONT_PROXY_MATRIX: >-
  {{
    [
      { 'domain': MINIO_CONSOLE_DOMAIN, 'http_port': MINIO_CONSOLE_PORT_PUBLIC },
      { 'domain': MINIO_API_DOMAIN,     'http_port': MINIO_API_PORT_PUBLIC }
    ]
  }}
