# xmpp is more a service then a app with ui interface. @todo Rename it 
server:
  domains:
    canonical:
      - xmpp.{{ DOMAIN_PRIMARY }}
    aliases: []
compose:
  services:
    logout:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
