public_api_activated:       False                                 # Security hole. Can be used for spaming                          # Docker Image version
server:
  domains:
    canonical:
      - "newsletter.{{ DOMAIN_PRIMARY }}"
    aliases: []
  status_codes:
    default: 404
  csp:
    flags:
      script-src-elem:
        unsafe-inline:  true
compose:
  services:
    asset:
      enabled:  true
      shared:   true
    oidc:
      enabled:  true
      shared:   true
    logout:
      enabled:  true
      shared: true
    dashboard:
      enabled:  true
      shared: true
    matomo:
      enabled:  true
      shared:   true
    email:
      enabled:  true
      shared:   true
    postgres:
      enabled: true
      shared: true
    listmonk:
      cpus:               1.0
      mem_reservation:    256m
      mem_limit:          1g
      pids_limit:         1024
      min_storage:        "5GB"
      image:              listmonk/listmonk
      version:            latest
      backup:
        no_stop_required: true
      name:               listmonk
      port:               9000
    css:
      enabled: true
      shared: true
    hcaptcha:
      enabled: "{{ HCAPTCHA_ENABLED | bool }}"
    prometheus:
      enabled: true
      shared: true
credentials:
  hcaptcha:
    key:    "{{ CAPTCHA.HCAPTCHA.KEY | default('') }}"
    secret: "{{ CAPTCHA.HCAPTCHA.SECRET | default('') }}"
