username: coturnconsumer
server:
  domains:
    canonical:
      - "coturn.{{ DOMAIN_PRIMARY }}"
compose:
  services:
    matomo:
      enabled: true
      shared: true
    coturn:
      enabled:            false
      shared:             true
      image:              "coturn/coturn"
      version:            "latest"
      min_storage:        "1GB"
      user_auth_enabled:  false
      cpus:               1.0
      mem_reservation:    512m
      mem_limit:          1g
      pids_limit:         256
      network_mode:       host
    redis:
      backup:
        disabled: true
      enabled:            false
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
