titel:              "Mobilizon on {{ DOMAIN_PRIMARY | upper }}"
server:
  csp:
    flags:
      script-src-elem:
        unsafe-inline:  true
      script-src-attr:
        unsafe-eval:  true
  domains:
    canonical:
      - "event.{{ DOMAIN_PRIMARY }}"
    aliases: []
    
compose:
  services:
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    postgres:
      enabled: true
      shared: true
    mobilizon:
      image:    "docker.io/kaihuri/mobilizon"
      name:     "mobilizon"
      version:  "5.2.3"
      min_storage:  "5GB"
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
