compose:
  services:
    mini-qr:
      image:   ghcr.io/lyqht/mini-qr
      version: latest
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    redis:
      backup:
        disabled: true
      enabled:  false
    css:
      enabled: true
      shared: true
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
server:
  csp:
    whitelist:
      script-src-elem:
        # Propably some tracking code
        # Anyhow implemented to pass CSP checks
        # @todo Remove
        - https://*.clarity.ms/
      connect-src:
        - https://*.clarity.ms
        - "data:"
      style-src-elem: []
      font-src: []
      frame-ancestors: [] 
    flags:
      style-src-attr:
        unsafe-inline:  true
      script-src-elem:
        unsafe-inline:  true
      script-src-attr:
        unsafe-eval:    true
  domains:
    canonical:
      - "qr.{{ DOMAIN_PRIMARY }}"
    aliases: []
