server:
  csp:
    flags:
      script-src-attr:
        unsafe-eval: true
    whitelist:  
      manifest-src: "auth.{{ DOMAIN_PRIMARY }}"
  domains:
    aliases: []
    canonical:
      - suite.crm.{{ DOMAIN_PRIMARY }}
email:
  from_name: "Customer Relationship Management (SuiteCRM, {{ DOMAIN_PRIMARY }})"

compose:
  services:
    oidc:
      enabled: false
      shared: false
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    mariadb:
      enabled: true
      shared: true
    suitecrm:
      image:            "php"
      # TODO: Make SuiteCRM compatible with PHP 8.5; update currently not possible. noqa: intentional legacy pin
      # nocheck: docker-version
      version:          "8.2-apache"
      # Git tag from https://github.com/SuiteCRM/SuiteCRM-Core/releases
      app_version:      "8.9.1"
      name:             "suitecrm"
      min_storage:      "10GB"
      cpus:             1.5
      mem_reservation:  1.2g
      mem_limit:        2g
      pids_limit:       768
    oauth2:
      enabled: true
      shared: true
      origin:
        host:           "suitecrm"
        port:           "80"
    css:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:       suitecrm_data

maintenance_mode: false
