site_titel:           "Academy on {{ DOMAIN_PRIMARY }}"
server:
  csp:
    flags:
      script-src-elem:
        unsafe-inline:  true
        unsafe-eval:    true
      script-src-attr:
        unsafe-eval:    true
      style-src-attr:
        unsafe-inline:  true
        unsafe-eval:    true
    whitelist:
      font-src:
        - "data:"
        - "blob:"
      script-src-elem:
        - "https://cdn.jsdelivr.net"
  domains:
    canonical:
      - "academy.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    mariadb:
      enabled: true
      shared: true
    moodle:
      # nocheck: docker-version
      version:            "4.5" # Latest LTS - Necessary for OIDC
      image:              bitnamilegacy/moodle
      name:               moodle
      min_storage:        "10GB"
      cpus:               1.0
      mem_reservation:    1g
      mem_limit:          2g
      pids_limit:         512
    css:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:             moodle_data
    code:             moodle_code
  
