---
- name: "load docker, db and proxy for {{ application_id }}"
  include_role:
    name: sys-stk-full
  vars:
    docker_compose_flush_handlers: true

- name: Wait for Gitea HTTP endpoint
  wait_for:
    host: "{{ DOCKER_REACH_HOST }}"
    port: "{{ ports.localhost.http[application_id] }}"
    delay: 5
    timeout: 300

- name: Patch Gitea database settings in app.ini
  include_tasks: 01_database.yml

- name: "Run DB migrations inside Gitea container"
  shell: |
    container exec -i --user {{ GITEA_USER }} {{ GITEA_CONTAINER }} \
      /app/gitea/gitea migrate
  args:
    chdir: "{{ lookup('container', application_id, 'directories.instance') }}"
  register: migrate
  changed_when: "'migrations completed' in migrate.stdout"

- name: "Create initial admin user"
  shell: |
    container exec -i --user {{ GITEA_USER }} {{ GITEA_CONTAINER }} \
      /app/gitea/gitea admin user create \
        --admin \
        --username "{{ lookup('users', 'administrator').username }}" \
        --password {{ lookup('users', 'administrator').password | quote }} \
        --email    "{{ lookup('users', 'administrator').email }}" \
        -c {{ GITEA_CONFIG }}
  args:
    chdir: "{{ lookup('container', application_id, 'directories.instance') }}"
  register: create_admin
  changed_when: "'has been successfully created' in create_admin.stdout"
  failed_when: create_admin.rc != 0 and 'user already exists' not in create_admin.stderr

- name: "Wait until Gitea setup and migrations are ready"
  uri_retry:
    url: "http://{{ DOCKER_REACH_HOST }}:{{ ports.localhost.http[application_id] }}/api/v1/version"
    method: GET
    status_code: 200
    return_content: no
  register: gitea_ready
  until: gitea_ready.status == 200
  retries: 20
  delay: 5
  when: (GITEA_OIDC_ENABLED | bool) or (GITEA_LDAP_ENABLED | bool)

- name: Execute Setup Routines
  include_tasks: 02_setup.yml

- name: Execute Cleanup Routines
  include_tasks: 03_cleanup.yml 
  when: MODE_CLEANUP | bool

- name: Include DNS role to register Gitea domain(s)
  include_role:
    name: sys-dns-cloudflare-records
  vars:
    cloudflare_records:
      - zone:     "{{ lookup('domain',application_id) | to_zone }}"
        type:     A
        name:    "{{ lookup('domain',application_id) }}"
        content: "{{ networks.internet.ip4 }}"
        proxied: false  # Necessary for SSH port
  when: DNS_PROVIDER == 'cloudflare'
