server:
  domains:
    canonical:
      - "html.{{ DOMAIN_PRIMARY }}"
    aliases: []
  status_codes:
    default:
      - 403 # On initialisation, there is no index.html deployed
      - 200
compose:
  services:
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
