api_suffix:             "/bigbluebutton/"
server:
  ip6_enabled:          "{{ NETWORK_IPV6_ENABLED | bool }}"
  csp:
    flags:
      script-src-elem:
        unsafe-inline:  true
      style-src-attr:
        unsafe-inline:  true
  domains:
    canonical:
      - "meet.{{ DOMAIN_PRIMARY }}"
    aliases: []
credentials: {}

compose:
  services:
    oidc:
      enabled:  true
      shared:   true
    logout:
      enabled:  true
      shared: true
    ldap:
      enabled:  false
    dashboard:
      enabled:  false
    matomo:
      enabled:  true
      shared:   true
    email:
      enabled: true
      shared: true
    bigbluebutton:
      repository:     "https://github.com/bigbluebutton/docker.git"
      version:        "main"
      recording:
        enabled:      false  # Enable recordings of sessions (deactivated by  default because it crashed, also check GDPR comnpliance)
        cleanup:      true  # Auto-Cleanup Recordings
        max_age_days: 30    # Cleanup recording after this amount of days
      min_storage:    50GB
    # noqa: shared
    postgres:
      shared:   false
      enabled:  true
    greenlight:
      enabled:  true
      shared: false
    coturn:
      shared:   true
      enabled:  true 
    collabora:
      shared:   true
      enabled:  true
    css:
      enabled:  true
      shared: true
    prometheus:
      enabled: true
      shared: true
