credentials: {}
compose:
  services:
    oidc:
      enabled: false
      shared: false
    logout:
      enabled: true
      shared: true

    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    # noqa: shared
    postgres:
      enabled: true
      shared: true
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled:  true
    bookwyrm:
      version:    'v0.7.5'
      name:       bookwyrm
      repository: https://github.com/bookwyrm-social/bookwyrm.git
      min_storage: "15GB"
      base_image:   python
      base_version: "3.11-bookworm"
    # noqa: shared
    worker:
      enabled:  true
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:       "bookwyrm_data"
    media:      "bookwyrm_media"
server:
  csp:
    whitelist: {}
    flags:
      script-src-elem:
        unsafe-inline:  true
      script-src-attr:
        unsafe-inline:  true
  domains:
    canonical:
      - "book.{{ DOMAIN_PRIMARY }}"
    aliases: []
rbac:
  roles: {}
registration_open: false
allow_invite_request: false
