compose:
  services:
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    lam:
      image:        ghcr.io/ldapaccountmanager/lam
      version:      latest
      min_storage:  "1GB"
    oauth2:
      enabled: true
      shared: true
      origin:
        host:       application
        port:       80
      allowed_groups:
        - "{{ [RBAC.GROUP.NAME, 'web-app-lam-administrator'] | path_join }}"
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
server:
  csp:
    flags:
      style-src-attr:
        unsafe-inline:  true
      script-src-elem:
        unsafe-inline:  false
        unsafe-eval:    true
      script-src-attr:
        unsafe-inline:  true
  domains:
    aliases: []
    canonical:
      - lam.{{ DOMAIN_PRIMARY }}
