---

- name: "Ensure base directory"
  ansible.builtin.file:
    path: "{{ DIR_SECRETS }}"
    state: directory
    owner: "{{ SYS_TOKEN_STORE_OWNER }}"
    group: "{{ SYS_TOKEN_STORE_GROUP }}"
    mode: "{{ SYS_TOKEN_STORE_DIR_MODE }}"
  become: true

- name: "Ensure store file exists"
  ansible.builtin.file:
    path: "{{ FILE_TOKENS }}"
    state: touch
    owner: "{{ SYS_TOKEN_STORE_OWNER }}"
    group: "{{ SYS_TOKEN_STORE_GROUP }}"
    mode: "{{ SYS_TOKEN_STORE_FILE_MODE }}"
  become: true

- name: "Load existing store"
  ansible.builtin.import_tasks: 02_load.yml

- include_tasks: utils/once/flag.yml
