server:
  csp:
    flags:
      script-src-elem:
        unsafe-inline:              true
      style-src-attr:
        unsafe-inline:              true
    whitelist:
      font-src:
        - "data:"
        - "blob:"
      worker-src:
        - "blob:"
      manifest-src:
        - "data:"
  domains:
    aliases: []
    canonical:
      - tea.git.{{ DOMAIN_PRIMARY }}
compose:
  services:
    oidc:
      enabled: false
      shared: false
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    mariadb:
      enabled: true
      shared: true
    gitea:
      image:            "gitea/gitea"
      version:          "latest"
      min_storage:      "10GB"
      backup:
        no_stop_required: true
      port:               3000
      name:               "gitea"
      cpus:               1.0
      mem_reservation:    1g
      mem_limit:          2g
      pids_limit:         1024
      title:              "{{ SOFTWARE_NAME }} Code Hub" # @todo load automatic based on service_porvider infos
      configuration:
        repository:
          enable_push_create_user:      True      # Allow users to push local repositories to Gitea and have them automatically created for a user.
          default_private:              last      # Default private when creating a new repository: last, private, public
          default_push_create_private:  True      # Default private when creating a new repository with push-to-create.
    redis:
      backup:
        disabled: true
      enabled:            false
      cpus:               0.25
      mem_reservation:    0.2g
      mem_limit:          0.3g
      pids_limit:         512
    oauth2:
      origin:
        host:             "application"
        port:             "{{ lookup('config', 'web-app-gitea', 'compose.services.gitea.port') }}"
      acl:
        blacklist:
          - "/user/login"
      enabled: false
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
      native_metrics:
        enabled:    true
        port:       3000     # Gitea metrics are on the main HTTP server port (same as app)
  volumes:
    data:             "gitea_data"
