server:
  domains:
    canonical:
      - "collabora.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    whitelist:
      frame-ancestors:
        - "*.{{ DOMAIN_PRIMARY }}"
    flags:
      style-src-attr:
        unsafe-inline:  true
compose:
  services:
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    redis:
      backup:
        disabled: true
      enabled: false
    collabora:
      enabled:          false
      shared:           true
      image:            collabora/code
      version:          latest
      name:             collabora
      min_storage:      "10GB"
      cpus:             2
      mem_reservation:  1g
      mem_limit:        2g
      pids_limit:       2048
    prometheus:
      enabled: true
      shared: true
