repository:           "repository"  # Name of the repository folder                 
server:
  csp:
    flags:
      style-src-attr:
        unsafe-inline: true
      script-src-elem:
        unsafe-inline: true
    whitelist:
      font-src:
        # Allow also http connections
        - "http://forum.{{ DOMAIN_PRIMARY }}"
  domains:
    canonical:
      - "forum.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    asset:
      enabled: true
      shared: true
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    ldap:
      enabled: false
      shared:  false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    # noqa: shared
    postgres:
      enabled: true
      shared: true
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled:    true
    discourse:
      name:               "discourse"
      version:            "main" # No version tag on container image exists :(
      min_storage:        "15GB"
# Impossible to don't stop due to 'test_backup_no_stop_required_consistency' :(
#      backup:
#        no_stop_required: true
      repository:         "https://github.com/discourse/discourse_docker.git"
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes: 
    data:   discourse_data
  network:  discourse
plugins:
  docker_manager:
    enabled: true
  discourse-activity-pub:
    enabled:  true
  discourse-akismet:
    enabled:  true
# The following plugins moved to the default setup
#  discourse-cakeday:
#    enabled:  true
#  discourse-solved:
#    enabled:  true 
#  discourse-voting:
#    enabled:  true
