compose:
  services:
    oidc:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    # noqa: shared
    redis:
      backup:
        disabled: true
      enabled:      true
    postgres:
      enabled: true
      shared: true
    gitlab:
      image:            "gitlab/gitlab-ee"
      version:          "latest"
      name:             "gitlab"
      min_storage:      "30GB"
      cpus:             "4.0"
      mem_reservation:  "8g"
      mem_limit:        "12g"
      pids_limit:        4096
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
  volumes:
    data:           "gitlab_data"
    logs:           "gitlab_logs"
    config:         "gitlab_config"
server:
  domains:
    canonical:
      - lab.git.{{ DOMAIN_PRIMARY }}
  csp:
    flags:
      script-src-elem:
        unsafe-inline:  true
