import sys
import unittest
from pathlib import Path

sys.path.insert(
    0,
    str(
        Path(
            str(
                Path(str(Path(__file__).parent))
                / "../../../../../../roles/web-app-bigbluebutton/filter_plugins"
            )
        ).resolve()
    ),
)

from compose_mods import compose_mods

from utils.cache.yaml import load_yaml_str
from utils.domains.default_primary import default_domain_primary

DOMAIN = default_domain_primary()


def sort_dict(obj):
    if isinstance(obj, dict):
        return {k: sort_dict(obj[k]) for k in sorted(obj)}
    if isinstance(obj, list):
        return [sort_dict(v) for v in obj]
    return obj


class TestComposeModsFullFile(unittest.TestCase):
    def setUp(self):
        self.compose_repository_path = "/opt/compose/bigbluebutton/services/repository"
        self.env_file = "/opt/compose/bigbluebutton/.env/env"
        self.original = """# auto generated by ./scripts/generate-compose
# don't edit this directly.

services:
  bbb-web:
    build:
      context: mod/bbb-web
      additional_contexts:
        - src-web=./repos/bigbluebutton/bigbluebutton-web
    volumes:
      - ./data/bigbluebutton:/var/bigbluebutton
      - ./data/freeswitch-meetings:/var/freeswitch/meetings

  freeswitch:
    build:
      context: mod/freeswitch
      additional_contexts:
        - freeswitch=./repos/freeswitch/
    volumes:
      - ./data/freeswitch-meetings:/var/freeswitch/meetings

  nginx:
    build:
      context: mod/nginx

  redis:
    image: redis:7.2-alpine

  coturn:
    image: coturn/coturn:4.6-alpine
    volumes:
      - ./mod/coturn/turnserver.conf:/etc/coturn/turnserver.conf

  bbb-graphql-server:
    build:
      context: mod/bbb-graphql-server
"""

        self.expected = """services:
  bbb-web:
    build:
      context: /opt/compose/bigbluebutton/services/repository/mod/bbb-web
      additional_contexts:
        - src-web=/opt/compose/bigbluebutton/services/repository/repos/bigbluebutton/bigbluebutton-web
    volumes:
      - /opt/compose/bigbluebutton/services/repository/data/bigbluebutton:/var/bigbluebutton
      - /opt/compose/bigbluebutton/services/repository/data/freeswitch-meetings:/var/freeswitch/meetings
    env_file:
      - /opt/compose/bigbluebutton/.env/env

  freeswitch:
    build:
      context: /opt/compose/bigbluebutton/services/repository/mod/freeswitch
      additional_contexts:
        - freeswitch=/opt/compose/bigbluebutton/services/repository/repos/freeswitch/
    volumes:
      - /opt/compose/bigbluebutton/services/repository/data/freeswitch-meetings:/var/freeswitch/meetings
    env_file:
      - /opt/compose/bigbluebutton/.env/env

  nginx:
    build:
      context: /opt/compose/bigbluebutton/services/repository/mod/nginx
    env_file:
      - /opt/compose/bigbluebutton/.env/env

  redis:
    image: redis:7.2-alpine
    env_file:
      - /opt/compose/bigbluebutton/.env/env

  coturn:
    image: coturn/coturn:4.6-alpine
    volumes:
      - /opt/compose/bigbluebutton/services/repository/mod/coturn/turnserver.conf:/etc/coturn/turnserver.conf
    env_file:
      - /opt/compose/bigbluebutton/.env/env

  bbb-graphql-server:
    build:
      context: /opt/compose/bigbluebutton/services/repository/mod/bbb-graphql-server
    env_file:
      - /opt/compose/bigbluebutton/.env/env
"""

    def test_full_file_semantic_match(self):
        actual_data = load_yaml_str(
            compose_mods(self.original, self.compose_repository_path, self.env_file)
        )
        expected_data = load_yaml_str(self.expected)
        for key in expected_data:
            self.assertIn(key, actual_data)
            self.assertEqual(sort_dict(actual_data[key]), sort_dict(expected_data[key]))
        self.assertNotIn("volumes", actual_data)

    def test_extra_hosts_injected_except_host_network(self):
        original = """
services:
  greenlight:
    image: bigbluebutton/greenlight:v3
  freeswitch:
    network_mode: host
    image: bbb/freeswitch
  nginx:
    extra_hosts:
      - "existing.example:1.2.3.4"
  etherpad:
    extra_hosts:
      mapped.example: 5.6.7.8
"""
        data = load_yaml_str(
            compose_mods(
                original,
                self.compose_repository_path,
                self.env_file,
                extra_hosts=[f"auth.{DOMAIN}:host-gateway"],
            )
        )
        services = data["services"]
        self.assertIn(
            f"auth.{DOMAIN}:host-gateway", services["greenlight"]["extra_hosts"]
        )
        self.assertNotIn("extra_hosts", services["freeswitch"])
        self.assertEqual(
            services["nginx"]["extra_hosts"],
            ["existing.example:1.2.3.4", f"auth.{DOMAIN}:host-gateway"],
        )
        self.assertEqual(
            services["etherpad"]["extra_hosts"],
            ["mapped.example:5.6.7.8", f"auth.{DOMAIN}:host-gateway"],
        )

    def test_extra_hosts_absent_without_kwarg(self):
        data = load_yaml_str(
            compose_mods(self.original, self.compose_repository_path, self.env_file)
        )
        for svc in data["services"].values():
            self.assertNotIn("extra_hosts", svc)

    def test_build_stripped_only_when_prebuilt_image_present(self):
        original = """services:
  freeswitch:
    build:
      context: mod/freeswitch
    image: alangecker/bbb-docker-freeswitch:any-tag
  haproxy:
    build:
      context: mod/haproxy
    image: alangecker/bbb-haproxy:any-tag
  html5-dev:
    build:
      context: mod/html5-dev
  coturn:
    image: coturn/coturn:any-tag
"""
        services = load_yaml_str(
            compose_mods(original, self.compose_repository_path, self.env_file)
        )["services"]
        self.assertNotIn("build", services["freeswitch"])
        self.assertNotIn("build", services["haproxy"])
        self.assertIn("build", services["html5-dev"])
        self.assertEqual(
            services["html5-dev"]["build"]["context"],
            self.compose_repository_path + "/mod/html5-dev",
        )


if __name__ == "__main__":
    unittest.main()
