server:
  domains:
    canonical:
      - "bridgyfed.{{ DOMAIN_PRIMARY }}"
    aliases: []
  csp:
    whitelist: {}
    flags: {}

compose:
  services:
    oidc:
      enabled: false
      shared: false
    logout:
      enabled: false
      shared: false
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    application:
      image:      "python"
      version:    "3.14-bookworm"
      name:       "web-app-bridgy-fed"
      repository: "https://github.com/snarfed/bridgy-fed.git"
      branch:     "main"
    css:
      enabled: true
      shared: true
    # noqa: email
    email:
      enabled: false
      shared: false
    prometheus:
      enabled: true
      shared: true
rbac:
  roles: {}
 
